config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  # ERRORS
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'

  root to: 'pages#home'

  # USERS DEVISE
  devise_for :users
  # USERS NAMESPACE
  scope module: :users do
    resources :users, only: %i[show index] do
      resource :attributes, only: %i[edit update] do
        put :save_content, on: :member
      end
      resource :photo, only: %i[edit update]
    end
  end

  # BLOCKS NAMESPACE
  scope module: :blocks do
    # BLOCKS
    resources :users, only: [] do
      resources :blocks, except: [:index], shallow: true
    end

    resources :blocks, only: [] do
      put :order, on: :member
      # ITEMS
      resources :items, except: [:index], shallow: true do
        put :order, on: :member
      end
    end
    # ITEMS
    resources :item_contents, only: %i[show edit update] do
      put :save_content, on: :member
      get 'photos/:photo_id', to: 'item_contents#show_photo', on: :member, as: :photo
      get :photos, on: :member
    end
    get 'photos/:photo_id', to: 'item_contents#photo_partial', as: :photo_partial
  end

  # BLOG
  resources :users, only: [] do
    resources :posts, shallow: true do
      patch :publish, on: :member
      post :shift, on: :member
      put :save_content, on: :member
    end
  end

  # FILE UPLOADS
  resources :file_uploads, only: [:destroy]

  # WORKER (Github Cronjob)
  get '/refresh_sitemap', to: 'worker#refresh_sitemap'
end

app/views/shared/_current_session.html.erb
<meta name="current-person-id" content="<%= current_user ? current_user.id : '' %>">
<meta name="current-person-admin" content="<%= current_user ? current_user.admin : '' %>">
<meta name="current-person-user" content="<%= @user == current_user %>">
<meta name="show-action-btns" content="<%= @user == current_user %>">

app/views/shared/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove">
    <%= message %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer__links">
  </div>
  <div class="footer__copyright">
    Made with <i class="fas fa-heart"></i> by &copy;<a href="https://www.margareti.com" target="_blank">Margareti</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<header class="navbar" 
        data-controller="sidebar navbar"
        data-action="scroll@window->navbar#updateNavbar">
  <div class="navbar__brand">
    <%= link_to "🥥", root_path %>
  </div>
  <div class="navbar__name">
    <%= current_user.email_username if user_signed_in? %>
  </div>
  <button class="open-button button" data-action="click->sidebar#toggleOpen">
    <%= Icon.new("hamburger").call %>
  </button>
  <%= render partial: "shared/sidebar" %>
</header>

app/views/shared/_sidebar.html.erb
<div class="sidebar" 
      data-sidebar-target="toggle" data-action="click->sidebar#toggleClose">
  <div class="sidebar__container">
    <div class="sidebar__inner">
      <div class="sidebar__context">
    
        <button id="close-button" class="button" data-action="click->sidebar#toggleClose">
          <%= Icon.new("close").call %>
        </button>
    
        <ul>
          <% if user_signed_in? %>
            <%= sign_out_button("Sign out", destroy_user_session_path, "sign_out") %>
          <% else %>
            <%= sidebar_item("Sign in", new_user_session_path, "sign_in") %>
          <% end %>
          
          <%#= divider %> 
          
          <%#= sidebar_button(t("chats.new_chat"), new_chat_path, "send") %>           

          <%#= divider %> 

          <%# if current_user&.admin? %>
            <%#= admin_sidebar_button([
              { text: 'Dashboard', path: blazer_path }, 
              { text: 'Mailchimp translator', path: new_mailchimp_translation_path },
              { text: 'Users', path: users_path },
              { text: 'Contacts', path: contacts_path },
              { text: 'Sidekiq', path: sidekiq_web_path },
              { text: 'Test Export users CSV', path: '/exports/user/create.csv' }
            ]) %>
            <%#= divider %>
          <%# end %>
          
          <%# <li class="sidebar__item"> %>
            <%#= render "shared/language_links" %>
          <%# </li> %>
          <% if user_signed_in? %>
            <%= divider %> 
            <%#= user_profile_link(current_user) %>
            <%= sidebar_item("Blog", user_posts_path(current_user), "book") %> 
          <% end %>
            
          <%#= divider %> 
                    
          <%#= sidebar_item(t("pricing.pricing"), pricing_path, "dollar") %>
          <%#= sidebar_item(t("pages.about.about").capitalize, about_path, "info_black") %>
          <%#= sidebar_item(t("deepl_translations.multi_translator"), new_deepl_translation_path, "language") %>
          <%#= sidebar_item(t("posts.blog"), posts_path, "book") %>
          
          <%#= divider %> 
          
          <%#= sidebar_button_turbo(t("contacts.feedback"), new_contact_path, "mail") %>
        </ul>

      </div>
    </div>
  </div>
</div>

app/views/shared/_signup_prompt.html.erb
<div class="container container--more-narrow mt-xxl">
  <div class="empty-state">
    <p class="empty-state__text">
      Get your own <%= context %>
    </p>

    <%= link_to "Sign up",
              new_user_registration_path,
              class: "btn btn--primary",
              target: "_top" %>
  </div>
</div>

app/views/shared/_spinner.html.erb
<div class="spinner" role="status">
  <span class="visually-hidden">Loading...</span>
</div>

app/views/shared/_toggle_actions_btn.html.erb
<% if policy(user).edit? %>
  <div class="toggle-wrapper" data-controller="action-btns">
    <label class="visible-label button" for="action-btns"><%= Icon.call("edit") %></label>
    <input data-action-btns-target="checkbox" class="toggle" type="checkbox" value="0" id="action-btns" data-action="change->action-btns#toggleActionBtns">
    <label class="form-check-label" for="action-btns"></label>
  </div>
<% end %>