config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  # ERRORS
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'

  root to: 'pages#home'

  # USERS DEVISE
  devise_for :users
  # USERS NAMESPACE
  scope module: :users do
    resources :users, only: %i[show index] do
      resource :attributes, only: %i[edit update] do
        put :save_content, on: :member
      end
      resource :photo, only: %i[edit update]
    end
  end

  # BLOCKS NAMESPACE
  scope module: :blocks do
    # BLOCKS
    resources :users, only: [] do
      resources :blocks, except: [:index], shallow: true
    end

    resources :blocks, only: [] do
      put :order, on: :member
      # ITEMS
      resources :items, except: [:index], shallow: true do
        put :order, on: :member
      end
    end
    # ITEMS
    resources :item_contents, only: %i[show edit update] do
      put :save_content, on: :member
      get 'photos/:photo_id', to: 'item_contents#show_photo', on: :member, as: :photo
      get :photos, on: :member
    end
    get 'photos/:photo_id', to: 'item_contents#photo_partial', as: :photo_partial
  end

  # BLOG
  resources :users, only: [] do
    resources :posts, shallow: true do
      patch :publish, on: :member
      post :shift, on: :member
      put :save_content, on: :member
    end
  end

  # FILE UPLOADS
  resources :file_uploads, only: [:destroy]

  # WORKER (Github Cronjob)
  get '/refresh_sitemap', to: 'worker#refresh_sitemap'
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :name, presence: true

  acts_as_list scope: :user

  scope :ordered, -> { order(:position) }

  def items_have_content?
    items.any? { |item| item.content.present? || item.photos.attached? }
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :block
  has_one :user, through: :block
  has_many_attached :photos

  validates :name, presence: true

  acts_as_list scope: :block

  scope :ordered, -> { order(:position) }

  def has_content?
    content.present? || photos.attached?
  end

  def next_photo(current_photo)
    photo_in_cycle(current_photo, :next)
  end
  
  def previous_photo(current_photo)
    photo_in_cycle(current_photo, :prev)
  end
  
  private
  
  def photo_in_cycle(current_photo, direction)
    photos_attachments = photos.attachments.sort_by(&:id)
    current_index = photos_attachments.index(current_photo)
  
    new_index = case direction
                when :next
                  (current_index + 1) % photos_attachments.size
                when :prev
                  (current_index - 1) % photos_attachments.size
                else
                  current_index
                end
  
    photos_attachments[new_index]
  end
end

app/controllers/blocks/blocks_controller.rb
class Blocks::BlocksController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @block = Block.new
    authorize @user
  end

  def create
    @block = Block.new(block_params)
    @user = User.find(params[:user_id])
    @block.user = @user
    authorize @block, policy_class: UserPolicy
    
    if @block.save
      respond_to do |format|
        format.html { redirect_to user_path(@user) }
        format.turbo_stream 
      end
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @block = Block.find(params[:id])
    authorize @block, policy_class: UserPolicy
  end
  
  def update
    @block = Block.find(params[:id])
    authorize @block, policy_class: UserPolicy
    
    if @block.update(block_params)
      respond_to do |format|
        format.html { redirect_to user_path(current_user) }
        format.turbo_stream { flash.now[:notice] = "Block updated" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @block = Block.find(params[:id])
    authorize @block, policy_class: UserPolicy
    
    @block.destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user) }
      format.turbo_stream { flash.now[:notice] = "Block deleted" }
    end
  end

  def order
    @block = Block.find(params[:id])
    authorize @block, :update?, policy_class: UserPolicy

    @block.insert_at(params[:new_position])

    head :no_content
  end

  private

  def block_params
    params.require(:block).permit(:name)
  end
end

app/controllers/blocks/item_contents_controller.rb
class Blocks::ItemContentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :show_photo, :photo_partial, :photos]
  
  def show
    @item = Item.find(params[:id])
    authorize @item, policy_class: UserPolicy
  end

  def show_photo
    @item = Item.find(params[:id])
    authorize @item, :show?, policy_class: UserPolicy
    
    @photo = ActiveStorage::Attachment.find(params[:photo_id])

    respond_to do |format|
      format.html
      format.turbo_stream do
        render partial: "blocks/item_contents/photo", locals: { photo: @photo }
      end
    end
  end

  def photos
    @item = Item.find(params[:id])
    authorize @item, :show?, policy_class: UserPolicy
  end

  def photo_partial
    @photo = ActiveStorage::Attachment.find(params[:photo_id])
    authorize @photo, :show?, policy_class: UserPolicy
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item, policy_class: UserPolicy
  end

  def update
    @item = Item.find(params[:id])
    authorize @item, policy_class: UserPolicy

    # Filter out non-existent blob IDs before updating the item
    filtered_params = item_params_with_existing_blobs

    if @item.update(filtered_params)
      respond_to do |format|
        format.html { redirect_to user_path(@item.block.user) }
        format.turbo_stream {flash.now[:notice] = "Item updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def save_content
    @item = Item.find(params[:id])
    authorize @item, :update?, policy_class: UserPolicy

    if @item.update(content: params[:content])
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = "Item content saved" }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  private

  def item_params
    params.require(:item).permit(:content, photos: [])
  end

# Filter out non-existent blob IDs
def item_params_with_existing_blobs
  params.require(:item).permit(:content, photos: []).tap do |filtered_params|
    if filtered_params[:photos]
      # Decode and filter blob_signed_ids to only include existing blobs
      existing_blob_signed_ids = filtered_params[:photos].select do |signed_id|
        next if signed_id.blank?
        blob_id = ActiveStorage.verifier.verify(signed_id, purpose: :blob_id)
        ActiveStorage::Blob.where(id: blob_id).exists?
      end

      # Replace the photos array with the filtered list of signed IDs
      filtered_params[:photos] = existing_blob_signed_ids
    end
  end
end
end

app/controllers/blocks/items_controller.rb
class Blocks::ItemsController < ApplicationController
  def new
    @block = Block.find(params[:block_id])
    @item = Item.new
    authorize @block, policy_class: UserPolicy
  end

  def create
    @block = Block.find(params[:block_id])
    @item = Item.new(item_params)
    @item.block = @block
    authorize @item, policy_class: UserPolicy

    if @item.save
      respond_to do |format|
        format.html { redirect_to user_path(current_user) }
        format.turbo_stream { }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item, policy_class: UserPolicy
  end

  def update
    @item = Item.find(params[:id])
    authorize @item, policy_class: UserPolicy
    
    if @item.update(item_params)
      respond_to do |format|
        format.html { redirect_to user_path(@item.block.user) }
        format.turbo_stream {flash.now[:notice] = "Item updated." }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item, policy_class: UserPolicy
    
    @item.destroy
    
    respond_to do |format|
      format.html { redirect_to user_path(@item.block.user) }
      format.turbo_stream { flash.now[:notice] = "Item deleted." }
    end
  end

  def order
    @item = Item.find(params[:id])
    authorize @item, :update?, policy_class: UserPolicy

    @item.update(block_id: params[:new_block_id])
    @item.insert_at(params[:new_position])

    head :no_content
  end

  private

  def item_params
    params.require(:item).permit(:name, :content)
  end
end

app/controllers/users/blocks_controller.rb
class Users::BlocksController < ApplicationController
  def new
    @block = Block.new
  end

  def create
    @block = Block.new(block_params)
    @user = User.find(params[:user_id])
    @block.user = @user

    if @block.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    @block = Block.find(params[:id])
    @block.destroy
    redirect_to user_path(current_user)
  end

  private

  def block_params
    params.require(:block).permit(:name, :position)
  end
end

app/helpers/blocks_helper.rb
module BlocksHelper
  def actions_for(object)
    edit_path = object.is_a?(Block) ? edit_block_path(object) : edit_item_path(object)
    delete_path = object.is_a?(Block) ? block_path(object) : item_path(object)
    
    html = ''.html_safe
  
    html << link_to("#", class: "sortable-handle", data: { controller: "action-authorisations", action_authorisations_target: "user"}) do
      Icon.call("drag")
    end

    html << link_to(edit_path, class: "action-btn", data: { controller: "action-authorisations", action_authorisations_target: "user"}) do
      Icon.call("edit")
    end
  
    html << button_to(delete_path, method: :delete, data: { turbo_confirm: "Are you sure?", controller: "action-authorisations", action_authorisations_target: "user" }, class: "button action-btn") do
      Icon.call("trash")
    end
  
    html
  end

  def accordion_toggle_btn(item)
    # if item.content.present?
      content_tag :div, Icon.call("plus"), data: { action: "click->accordion#toggle", accordion_target: "icon", action_authorisations_target: "accordion" }, class: "button"
    # end
  end

  def item_content_edit_btn(item)
    return unless item.has_content?
   
    content_tag :div, data: { controller: "action-authorisations", action_authorisations_target: "user" }, class: "block__item__content--edit flex-end" do
      link_to edit_item_content_path(item, data: { turbo_frame: nested_dom_id(item, "edit_content") }, class: "action-btn") do
        Icon.call("edit")
      end
    end
  end
end

app/views/blocks/items/_form.html.erb
<%= simple_form_for([block, item].compact) do |f| %>
  <%= form_error_notification(item) %>
  <div class="form__container" data-controller="add-url">
    <%= f.input :name, 
          input_html: { data: { controller: "autofocus", add_url_target: "input" } },
          wrapper_html: { class: "form__container__input--item-name"} %>
    <div class="form__container__actions">
      <%= link_to user_path(item.new_record? ? block.user : item.user), 
          data: { turbo_frame: item.new_record? ? nested_dom_id(block, "items") : dom_id(item) },
          class: "btn btn--light btn--emoji" do %>
        <%= Icon.call("cancel_emoji") %>
      <% end %>
      <%= button_tag(class: "btn btn--primary btn--emoji") do %>
        <%= Icon.new("confirm_emoji").call %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/blocks/items/_item.html.erb
<%= turbo_frame_tag dom_id(item), data: { sortable_url: order_item_path(item) }, class: "drag-item" do %>
  <div data-controller="accordion action-authorisations" 
      data-accordion-open-accordion-value="<%= open_accordion %>"
      data-has-expandable-content="<%= item.has_content? %>"
      class="block__item">
    
    <%= render "blocks/items/item_edit", item: item %>
    
    <div data-accordion-target="dropdown" class="block__item__content visually-hidden">
      <%= turbo_frame_tag nested_dom_id(item, "content"), src: item_content_path(item), loading: "lazy" do %>
        <%= render "shared/spinner" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/blocks/items/_item_edit.html.erb
<%= turbo_frame_tag nested_dom_id(item, "edit") do %>
  <div class="block__item__title">
    <div class="block__item__title--text">
      <%= markdown_links_to_html item.name %>
    </div>
    <%= actions_for(item) %>
    <%= accordion_toggle_btn(item) %>
  </div>
<% end %>

app/views/blocks/items/create.turbo_stream.erb
<%= turbo_stream.append nested_dom_id(@block, "items") do %>
  <%= render "blocks/items/item", item: @item, open_accordion: false %>
<% end %>
<%= turbo_stream.update nested_dom_id(@block, Item.new), "" %>
<%= turbo_stream.append nested_dom_id(@block, "items") do %>
  <%= render "blocks/blocks/add_item", block: @block %>
<% end %>

app/views/blocks/items/destroy.turbo_stream.erb
<%= turbo_stream.remove @item %>
<%= render_turbo_stream_flash_messages %>

app/views/blocks/items/edit.html.erb
<h1>Edit item <%= @item.name %></h1>

<%= turbo_frame_tag nested_dom_id(@item, "edit") do %>
  <%= render "form", block: nil, item: @item %>
<% end %>

app/views/blocks/items/new.html.erb
<h1>New item for <%= @block.name %></h1>

<%= turbo_frame_tag nested_dom_id(@block, @item) do %>
  <%= render "form", block: @block, item: @item %>
<% end %>

app/views/blocks/items/update.turbo_stream.erb
<%= turbo_stream.replace nested_dom_id(@item, "edit") do %>
  <%= render "blocks/items/item_edit", item: @item %>
<% end %>
<%= render_turbo_stream_flash_messages %>