config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check
  # ERRORS
  match '/404', via: :all, to: 'errors#not_found'
  match '/500', via: :all, to: 'errors#internal_server_error'

  root to: 'pages#home'

  # USERS DEVISE
  devise_for :users
  # USERS NAMESPACE
  scope module: :users do
    resources :users, only: %i[show index] do
      resource :attributes, only: %i[edit update] do
        put :save_content, on: :member
      end
      resource :photo, only: %i[edit update]
    end
  end

  # BLOCKS NAMESPACE
  scope module: :blocks do
    # BLOCKS
    resources :users, only: [] do
      resources :blocks, except: [:index], shallow: true
    end

    resources :blocks, only: [] do
      put :order, on: :member
      # ITEMS
      resources :items, except: [:index], shallow: true do
        put :order, on: :member
      end
    end
    # ITEMS
    resources :item_contents, only: %i[show edit update] do
      put :save_content, on: :member
      get 'photos/:photo_id', to: 'item_contents#show_photo', on: :member, as: :photo
      get :photos, on: :member
    end
    get 'photos/:photo_id', to: 'item_contents#photo_partial', as: :photo_partial
  end

  # BLOG
  resources :users, only: [] do
    resources :posts, shallow: true do
      patch :publish, on: :member
      post :shift, on: :member
      put :save_content, on: :member
    end
  end

  # FILE UPLOADS
  resources :file_uploads, only: [:destroy]

  # WORKER (Github Cronjob)
  get '/refresh_sitemap', to: 'worker#refresh_sitemap'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  acts_as_list scope: :user

  validates :title, :body, presence: true

  scope :ordered, -> { order(position: :asc) }
  scope :published, -> { where(published: true) }

  def published_icon
    if published
      Icon.call('published')
    else
      Icon.call('unpublished')
    end
  end

  def keyword_subtitle
    subtitle.truncate(300).split(' ').join(', ') if subtitle.present?
  end

  def keyword_title
    title.split(' ').join(', ')
  end

  def keywords
    keyword_subtitle || keyword_title
  end

  def shift(direction)
    case direction
    when 'up'
      other_post = user.posts.where('position < ?', position).ordered.last
      other_post&.increment_position
      decrement_position
    when 'down'
      other_post = user.posts.where('position > ?', position).ordered.first
      other_post&.decrement_position
      increment_position
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_post, only: %i[show edit update destroy publish shift save_content]

  def index
    @user = User.find(params[:user_id])
    @posts = policy_scope(Post).ordered.where(user: @user)

    index_meta_tags(@user)
    # @canonical_href = posts_url
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.build
    authorize @post
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.build(post_params)
    authorize @post

    if @post.save
      redirect_to post_path(@post), notice: 'Post created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    authorize @post

    show_meta_tags(@post)
    # @canonical_href = post_url(@post)
  end

  def edit
    authorize @post
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to post_path(@post)
      flash[:notice] = 'Post updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @post

    @post.destroy

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Post #{@post.title} destroyed" }
      format.html { redirect_to user_posts_path(@post.user), notice: 'Post destroyed' }
    end
  end

  def publish
    authorize @post, :update?

    @post.toggle!(:published)
    state = @post.published? ? 'published' : 'unpublished'

    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = "Post #{@post.title} #{state}" }
      format.html { redirect_to post_path(@post), notice: "Post #{state}" }
    end
  end

  def shift
    authorize @post, :update?

    @post.shift(params[:direction])

    redirect_to user_posts_path(current_user)
  end

  def save_content
    authorize @post, :update?

    if @post.update(body: params[:content])
      respond_to do |format|
        format.turbo_stream { flash.now[:notice] = 'Post content saved' }
        format.html { redirect_to edit_post_path(@post), notice: 'Post content saved' }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
      :title,
      :subtitle,
      :body
    )
  end

  def index_meta_tags(user)
    set_meta_tags title: "#{user.name}'s posts",
                  description: user.posts.any? ? user.posts.map(&:title).join(', ') : 'A space to blog about your work and your ideas',
                  keywords: 'portfolio, ideas, projects, showcase, work, blog, article',
                  og: {
                    title: "#{user.name}'s posts",
                    description: user.posts.any? ? user.posts.map(&:title).join(', ') : 'A space to blog about your work and your ideas',
                    type: 'website',
                    url: user_posts_url(user),
                    image: user.photo.attached? ? url_for(user.photo) : nil
                  },
                  twitter: {
                    card: 'summary',
                    site: '@yourportfolio',
                    title: "#{user.name}'s posts",
                    description: user.posts.any? ? user.posts.map(&:title).join(', ') : 'A space to blog about your work and your ideas',
                    image: user.photo.attached? ? url_for(user.photo) : nil
                  }
  end

  def show_meta_tags(post)
    set_meta_tags title: post.title,
                  description: post.subtitle.presence || post.body.truncate(300),
                  keywords: post.keywords,
                  og: {
                    title: post.title,
                    description: post.subtitle.presence || post.body.truncate(300),
                    type: 'website',
                    url: post_url(post),
                    image: post.user.photo.attached? ? url_for(post.user.photo) : nil
                  },
                  twitter: {
                    card: 'summary',
                    site: '@yourportfolio',
                    title: post.title,
                    description: post.subtitle.presence || post.body.truncate(300),
                    image: post.user.photo.attached? ? url_for(post.user.photo) : nil
                  }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def index_actions_for(post)
    html = ''.html_safe

    html << content_tag(:div, data: { controller: 'action-authorisations', action_authorisations_target: 'user' }) do
      button_to(shift_post_path(post, direction: 'up'), target: '_top', class: 'button') do
        Icon.call('up')
      end +
        button_to(shift_post_path(post, direction: 'down'), target: '_top', class: 'button') do
          Icon.call('down')
        end
    end

    html << link_to(edit_post_path(post), target: '_top',
                                          data: { controller: 'action-authorisations', action_authorisations_target: 'user' }) do
      Icon.call('edit')
    end

    html << button_to(post_path(post), method: :delete,
                                       data: { turbo_confirm: 'Are you sure?', controller: 'action-authorisations', action_authorisations_target: 'user' }, class: 'button') do
      Icon.call('trash')
    end

    html
  end

  def form_back_link(post, user)
    if post.new_record?
      link_to sanitize('&larr; Back to posts'), user_posts_path(user)
    else
      link_to sanitize('&larr; Back to post'), post_path(post)
    end
  end

  def show_actions_for(post)
    html = ''.html_safe

    html << link_to(edit_post_path(post), target: '_top') do
      Icon.call('edit')
    end

    html << button_to(post_path(post), method: :delete,
                                       data: { controller: 'confirmation', action: 'click->confirmation#confirm', turbo: false }, class: 'button') do
      Icon.call('trash')
    end

    html
  end
end

app/views/posts/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    There are no posts yet.
  </p>

  <% if policy(user).update? %>
    <%= link_to "Add post",
              new_user_post_path(user),
              class: "btn btn--dark",
              target: "_top" %>
  <% end %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for([user, post].compact) do |f| %>
  <div class="flex-end my-m form-top-btn">
    <%= f.button :submit, class: "btn btn--dark" %>
  </div>
  
  <%= form_error_notification(post) %>

  <div class="form-inputs">
    <%= f.input :title, input_html: { data: { controller: "autofocus" } } %>
    <%= f.input :subtitle,
          input_html: {
            data: {
              controller: "textarea-autogrow"
            } 
          } %>
    
    <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css"> 
    <%= f.input :body, 
          input_html: {
            data: { 
              controller: "markdown-editor",
              markdown_editor_url_value: rails_direct_uploads_url,
              markdown_editor_update_url_value: post.new_record? ? "" : save_content_post_path(post),
              markdown_editor_toolbar_value: [
                "undo", "redo", "bold", "italic", "strikethrough", "heading-1", "heading-2", "heading-3", "code", "quote", "unordered-list", "ordered-list", "link", "horizontal-rule", "preview", "side-by-side", "fullscreen", "guide"
              ]
            } 
          } %>
  </div>

  <div class="justify-space-between">
    <%= form_back_link(post, user) %>
    <%= f.button :submit, class: "btn btn--dark" %>
  </div>
<% end %>

app/views/posts/_meta.html.erb
<%# 
  set_meta_tags(
    title: translated_content_with_language(post.title),
    description: translated_content_with_language(post.subtitle),
    keywords: post.keywords ? post.keywords : t('application.meta_keywords'),
    separator: "&mdash;".html_safe,
    og: {
      title: translated_content_with_language(post.title),
      description: translated_content_with_language(post.subtitle),
      type: "website",
      url: request.original_url,
      image: post.image_or_default
    },
    twitter: {
      card: "summary_large_image",
      site: "translaite",
      title: translated_content_with_language(post.title),
      description: translated_content_with_language(post.subtitle),
      image: post.image_or_default
    }
  )
%>

app/views/posts/_post.html.erb
<%= content_tag :div, id: dom_id(post), class: "post__preview__container" do %>
  <div class="post__preview">
    <%= link_to post_path(post), target: "_top" do %>
      <h2 class="post__preview--title"><%= post.title %></h2>
      <h3 class="post__preview--subtitle"><%= post.subtitle %></h3>
    <% end %>
    <p class="post__meta">
      Posted by
      <%= link_to post.user.name, user_path(post.user), target: "_top" %>
      on
      <%= formatted_date post.created_at %>
    </p>
  </div>
  <% if policy(post).update? %>
    <div class="post__actions">
      <%= index_actions_for(post) %>
      <%= render "posts/publish_btn", post: post, position: "top" %>
    </div>
  <% end %>
<% end %>

app/views/posts/_publish_btn.html.erb
<%= turbo_frame_tag "post_#{post.id}_publish_btn_#{position}" do %>
  <%= button_to publish_post_path(post), 
      class: "button", 
      method: :patch, data: {} do %>
    <%= post.published_icon %>
  <% end %>
<% end %>

app/views/posts/destroy.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>

<%= turbo_stream.remove @post %>

app/views/posts/edit.html.erb
<div class="container container--narrow">
  <%= form_back_link(@post, nil) %>
  <div class="header">
    <h1>Edit post</h1>
  </div>

  <%= render 'form', user: nil, post: @post %>
</div>

app/views/posts/index.html.erb
<div class="container container--narrow">
  <%= link_to sanitize("&larr; Back home"), user_path(@user) %>

  <div class="header">
    <h1><%= @user.name %>'s posts</h1>
    <% if policy(@user).update? %>
      <%= link_to "New post",
      new_user_post_path(@user),
      data: {
        turbo_frame: :top,
      },
      class: "btn btn--dark" %>
    <% end %>
  </div>

  <%= turbo_frame_tag "posts" do %>
    <%= render "empty_state", user: @user %>
    <%= render @posts %>
  <% end %>
  <br>
  <%= link_to sanitize("&larr; Back home"), user_path(@user) %>
</div>

<%= render "shared/signup_prompt", context: "blog" %>

app/views/posts/new.html.erb
<div class="container container--narrow">
  <%= form_back_link(@post, @user) %>  
  <div class="header">
    <h1>New post</h1>
  </div>

  <%= render "form", user: @user, post: @post %>
</div>

app/views/posts/publish.turbo_stream.erb
<%= render_turbo_stream_flash_messages %>

<% positions = ["top", "middle", "bottom"] %>

<% positions.each do |position| %>
  <%= turbo_stream.replace "post_#{@post.id}_publish_btn_#{position}" do %>
    <%= render "posts/publish_btn", post: @post, position: position %>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<%= render "meta", post: @post %>

<div class="container container--more-narrow">
  <%= link_to sanitize("&larr; Back to posts"), user_posts_path(@post.user) %>
  <div class="header">
    <h1><%= @post.title %></h1>
    <% if policy(@post).update? %>
      <div class="post__actions">
        <%= show_actions_for(@post) %>
        <%= render "posts/publish_btn", post: @post, position: "top" %>
      </div>
    <% end %>
  </div>

  <div class="post__subtitle">
    <h3><%= simple_format @post.subtitle %></h3>
  </div>

  <div data-controller="markdown-clipboard" class="post__body markdown-content">
    <%= markdown @post.body %>
  </div>
  
  <%#= render "shared/sharer_btn", 
    url: post_url(@post), 
    title: translated_content_with_language(@post.title), 
    description: translated_content_with_language(@post.subtitle) %>
  <br>
  <div class="justify-space-between">
    <%= link_to sanitize("&larr; Back to posts"), user_posts_path(@post.user) %>
    <% if policy(@post).update? %>
      <div class="post__actions">
        <%= show_actions_for(@post) %>
        <%= render "posts/publish_btn", post: @post, position: "bottom" %>
      </div>
    <% end %>
  </div>
</div> 